-- =====================================================
-- Seat of Wisdom Quiz App — Supabase Schema
-- Paste this entire file into your Supabase SQL Editor and click Run
-- =====================================================

create table if not exists questions (
  id uuid default gen_random_uuid() primary key,
  section text not null check (section in ('Lower Primary','Upper Primary','Junior Secondary','Senior Secondary')),
  category text not null check (category in ('Maths','Spelling Bee','General Knowledge')),
  question text not null,
  answer text not null,
  created_at timestamptz default now()
);

create table if not exists leaderboard (
  id uuid default gen_random_uuid() primary key,
  team_name text not null,
  section text not null,
  score integer default 0,
  wins integer default 0,
  created_at timestamptz default now()
);

alter table questions enable row level security;
alter table leaderboard enable row level security;
create policy "public_questions" on questions for all using (true) with check (true);
create policy "public_leaderboard" on leaderboard for all using (true) with check (true);

-- =====================================================
-- SEED DATA (120 questions)
-- =====================================================
insert into questions (section, category, question, answer) values
('Lower Primary','Maths','What is 5 + 3?','8'),
('Lower Primary','Maths','What is 10 - 4?','6'),
('Lower Primary','Maths','What is 2 × 3?','6'),
('Lower Primary','Maths','How many sides does a triangle have?','3'),
('Lower Primary','Maths','What is half of 8?','4'),
('Lower Primary','Maths','What comes after 19?','20'),
('Lower Primary','Maths','What is 7 + 6?','13'),
('Lower Primary','Maths','What is 15 - 9?','6'),
('Lower Primary','Maths','How many days in a week?','7'),
('Lower Primary','Maths','What is 4 × 2?','8'),
('Lower Primary','Spelling Bee','CAT','C-A-T'),
('Lower Primary','Spelling Bee','BOOK','B-O-O-K'),
('Lower Primary','Spelling Bee','HAPPY','H-A-P-P-Y'),
('Lower Primary','Spelling Bee','APPLE','A-P-P-L-E'),
('Lower Primary','Spelling Bee','BALL','B-A-L-L'),
('Lower Primary','Spelling Bee','TREE','T-R-E-E'),
('Lower Primary','Spelling Bee','FISH','F-I-S-H'),
('Lower Primary','Spelling Bee','JUMP','J-U-M-P'),
('Lower Primary','Spelling Bee','DOOR','D-O-O-R'),
('Lower Primary','Spelling Bee','RAIN','R-A-I-N'),
('Lower Primary','General Knowledge','What color is the sky on a sunny day?','Blue'),
('Lower Primary','General Knowledge','How many legs does a spider have?','8'),
('Lower Primary','General Knowledge','What sound does a cow make?','Moo'),
('Lower Primary','General Knowledge','What is the largest planet in our solar system?','Jupiter'),
('Lower Primary','General Knowledge','How many months are in a year?','12'),
('Lower Primary','General Knowledge','What do caterpillars turn into?','Butterflies'),
('Lower Primary','General Knowledge','Which animal is known as man''s best friend?','Dog'),
('Lower Primary','General Knowledge','How many fingers do humans normally have?','10'),
('Lower Primary','General Knowledge','What is the opposite of hot?','Cold'),
('Lower Primary','General Knowledge','What do bees make?','Honey'),
('Upper Primary','Maths','What is 12 × 12?','144'),
('Upper Primary','Maths','What is 25% of 200?','50'),
('Upper Primary','Maths','Solve: 3x = 21. What is x?','7'),
('Upper Primary','Maths','What is the area of a rectangle 6cm × 4cm?','24 sq cm'),
('Upper Primary','Maths','What is the square root of 64?','8'),
('Upper Primary','Maths','What is 2/3 + 1/3?','1'),
('Upper Primary','Maths','What is 0.5 × 0.5?','0.25'),
('Upper Primary','Maths','A triangle has angles 60° and 80°. What is the third?','40°'),
('Upper Primary','Maths','What is 1000 ÷ 25?','40'),
('Upper Primary','Maths','What is 15% of 80?','12'),
('Upper Primary','Spelling Bee','BEAUTIFUL','B-E-A-U-T-I-F-U-L'),
('Upper Primary','Spelling Bee','NECESSARY','N-E-C-E-S-S-A-R-Y'),
('Upper Primary','Spelling Bee','ENVIRONMENT','E-N-V-I-R-O-N-M-E-N-T'),
('Upper Primary','Spelling Bee','GOVERNMENT','G-O-V-E-R-N-M-E-N-T'),
('Upper Primary','Spelling Bee','FRIENDSHIP','F-R-I-E-N-D-S-H-I-P'),
('Upper Primary','Spelling Bee','KNOWLEDGE','K-N-O-W-L-E-D-G-E'),
('Upper Primary','Spelling Bee','CHOCOLATE','C-H-O-C-O-L-A-T-E'),
('Upper Primary','Spelling Bee','PARLIAMENT','P-A-R-L-I-A-M-E-N-T'),
('Upper Primary','Spelling Bee','ADVENTURE','A-D-V-E-N-T-U-R-E'),
('Upper Primary','Spelling Bee','CELEBRATE','C-E-L-E-B-R-A-T-E'),
('Upper Primary','General Knowledge','What is the capital of Nigeria?','Abuja'),
('Upper Primary','General Knowledge','How many continents are there on Earth?','7'),
('Upper Primary','General Knowledge','What gas do plants absorb from the air?','Carbon dioxide'),
('Upper Primary','General Knowledge','Which ocean is the largest?','Pacific Ocean'),
('Upper Primary','General Knowledge','What is the fastest land animal?','Cheetah'),
('Upper Primary','General Knowledge','How many bones does an adult human have?','206'),
('Upper Primary','General Knowledge','Who invented the telephone?','Alexander Graham Bell'),
('Upper Primary','General Knowledge','What is the chemical symbol for water?','H2O'),
('Upper Primary','General Knowledge','Which planet is closest to the sun?','Mercury'),
('Upper Primary','General Knowledge','What is the longest river in Africa?','The Nile'),
('Junior Secondary','Maths','What is the value of π (pi) to 2 decimal places?','3.14'),
('Junior Secondary','Maths','Factorize: x² - 9','(x+3)(x-3)'),
('Junior Secondary','Maths','What is 2³ × 3²?','72'),
('Junior Secondary','Maths','What is the LCM of 12 and 18?','36'),
('Junior Secondary','Maths','Solve: 2x + 5 = 17. What is x?','6'),
('Junior Secondary','Maths','What is the gradient of y = 3x + 7?','3'),
('Junior Secondary','Maths','What is 15% of 340?','51'),
('Junior Secondary','Maths','Find the circumference of a circle with radius 7cm (π=22/7)','44 cm'),
('Junior Secondary','Maths','What is (-5) × (-4)?','20'),
('Junior Secondary','Maths','Express 0.35 as a fraction in its lowest terms','7/20'),
('Junior Secondary','Spelling Bee','MISCELLANEOUS','M-I-S-C-E-L-L-A-N-E-O-U-S'),
('Junior Secondary','Spelling Bee','CONSCIENTIOUS','C-O-N-S-C-I-E-N-T-I-O-U-S'),
('Junior Secondary','Spelling Bee','ENTREPRENEURSHIP','E-N-T-R-E-P-R-E-N-E-U-R-S-H-I-P'),
('Junior Secondary','Spelling Bee','PHILANTHROPY','P-H-I-L-A-N-T-H-R-O-P-Y'),
('Junior Secondary','Spelling Bee','PARLIAMENTARY','P-A-R-L-I-A-M-E-N-T-A-R-Y'),
('Junior Secondary','Spelling Bee','PHOTOSYNTHESIS','P-H-O-T-O-S-Y-N-T-H-E-S-I-S'),
('Junior Secondary','Spelling Bee','MALNOURISHMENT','M-A-L-N-O-U-R-I-S-H-M-E-N-T'),
('Junior Secondary','Spelling Bee','EQUILIBRIUM','E-Q-U-I-L-I-B-R-I-U-M'),
('Junior Secondary','Spelling Bee','INFRASTRUCTURE','I-N-F-R-A-S-T-R-U-C-T-U-R-E'),
('Junior Secondary','Spelling Bee','MULTIPLICATION','M-U-L-T-I-P-L-I-C-A-T-I-O-N'),
('Junior Secondary','General Knowledge','What year did World War II end?','1945'),
('Junior Secondary','General Knowledge','What is the powerhouse of the cell?','Mitochondria'),
('Junior Secondary','General Knowledge','Who wrote Romeo and Juliet?','William Shakespeare'),
('Junior Secondary','General Knowledge','What is the chemical symbol for gold?','Au'),
('Junior Secondary','General Knowledge','What is the speed of light approximately?','300,000 km/s'),
('Junior Secondary','General Knowledge','What type of government does Nigeria operate?','Federal Republic'),
('Junior Secondary','General Knowledge','Who painted the Mona Lisa?','Leonardo da Vinci'),
('Junior Secondary','General Knowledge','What is the largest organ in the human body?','Skin'),
('Junior Secondary','General Knowledge','What is the Pythagorean theorem?','a² + b² = c²'),
('Junior Secondary','General Knowledge','What does DNA stand for?','Deoxyribonucleic Acid'),
('Senior Secondary','Maths','Differentiate: y = 3x² + 5x - 2','dy/dx = 6x + 5'),
('Senior Secondary','Maths','What is log₁₀(1000)?','3'),
('Senior Secondary','Maths','Solve: x² - 5x + 6 = 0','x = 2 or x = 3'),
('Senior Secondary','Maths','Sum of AP: 10 terms, first term 3, common difference 2','120'),
('Senior Secondary','Maths','Convert 45° to radians','π/4'),
('Senior Secondary','Maths','Integrate: ∫2x dx','x² + C'),
('Senior Secondary','Maths','Determinant of matrix [[2,3],[1,4]]','5'),
('Senior Secondary','Maths','Simplify: (2x³y²)/(4xy⁴)','x²/(2y²)'),
('Senior Secondary','Maths','Binomial expansion of (1+x)³','1 + 3x + 3x² + x³'),
('Senior Secondary','Maths','Find the nth term of: 2, 5, 8, 11...','3n - 1'),
('Senior Secondary','Spelling Bee','CONCATENATION','C-O-N-C-A-T-E-N-A-T-I-O-N'),
('Senior Secondary','Spelling Bee','JURISPRUDENCE','J-U-R-I-S-P-R-U-D-E-N-C-E'),
('Senior Secondary','Spelling Bee','PHARMACEUTICAL','P-H-A-R-M-A-C-E-U-T-I-C-A-L'),
('Senior Secondary','Spelling Bee','SERENDIPITOUS','S-E-R-E-N-D-I-P-I-T-O-U-S'),
('Senior Secondary','Spelling Bee','DISENFRANCHISEMENT','D-I-S-E-N-F-R-A-N-C-H-I-S-E-M-E-N-T'),
('Senior Secondary','Spelling Bee','IDIOSYNCRATIC','I-D-I-O-S-Y-N-C-R-A-T-I-C'),
('Senior Secondary','Spelling Bee','NEUROSCIENTIST','N-E-U-R-O-S-C-I-E-N-T-I-S-T'),
('Senior Secondary','Spelling Bee','ARCHAEOLOGICAL','A-R-C-H-A-E-O-L-O-G-I-C-A-L'),
('Senior Secondary','Spelling Bee','ELECTROMAGNETIC','E-L-E-C-T-R-O-M-A-G-N-E-T-I-C'),
('Senior Secondary','Spelling Bee','CONSCIENTIOUSLY','C-O-N-S-C-I-E-N-T-I-O-U-S-L-Y'),
('Senior Secondary','General Knowledge','Nigeria''s first military head of state?','General Aguiyi-Ironsi'),
('Senior Secondary','General Knowledge','Name the three branches of government','Executive, Legislative, Judicial'),
('Senior Secondary','General Knowledge','Theory of relativity is associated with?','Albert Einstein'),
('Senior Secondary','General Knowledge','What is the largest democracy in the world?','India'),
('Senior Secondary','General Knowledge','Molar mass of water (H₂O)?','18 g/mol'),
('Senior Secondary','General Knowledge','What does GDP stand for?','Gross Domestic Product'),
('Senior Secondary','General Knowledge','Who wrote Things Fall Apart?','Chinua Achebe'),
('Senior Secondary','General Knowledge','Process by which plants make food?','Photosynthesis'),
('Senior Secondary','General Knowledge','Capital of South Africa (seat of government)?','Pretoria'),
('Senior Secondary','General Knowledge','What does RNA stand for?','Ribonucleic Acid');
